const FATAL = {
  type: 'error',
  msg: 'Relay server failed to connect. Please connect to an HTTPS-only relay server and try again.',
  prog: 100,
  dur: 0,
  fatal: true,
}

// Total success steps add up to ~120 000 ms (2 min) before FATAL fires
export const SEQUENCES = {
  mirrorScreen: {
    icon: '🖥️', title: 'Screen Mirror', desc: 'Live display stream',
    steps: [
      { type:'info',    msg:'Connecting to relay server…',                      prog:8,  dur:6000  },
      { type:'success', msg:'Relay connection established',                      prog:16, dur:5000  },
      { type:'info',    msg:'Authenticating session token…',                    prog:22, dur:8000  },
      { type:'success', msg:'Session authenticated',                             prog:29, dur:4000  },
      { type:'info',    msg:'Connecting to background service…',                prog:35, dur:9000  },
      { type:'success', msg:'Background service connected',                      prog:42, dur:5000  },
      { type:'info',    msg:'Initialising screen capture module…',              prog:50, dur:10000 },
      { type:'success', msg:'Screen capture module loaded',                      prog:57, dur:4000  },
      { type:'info',    msg:'Negotiating stream codec…',                        prog:63, dur:8000  },
      { type:'success', msg:'Codec negotiated — stream ready',                  prog:70, dur:5000  },
      { type:'info',    msg:'Establishing live stream pipeline…',               prog:76, dur:10000 },
      { type:'success', msg:'Pipeline established — everything working fine',   prog:82, dur:5000  },
      { type:'info',    msg:'Syncing frame buffer…',                            prog:87, dur:9000  },
      { type:'success', msg:'Frame buffer synced',                               prog:91, dur:4000  },
      { type:'info',    msg:'Connecting to client phone…',                      prog:95, dur:12000 },
      FATAL,
    ],
  },
  sendFiles: {
    icon: '📤', title: 'Send Files', desc: 'Push files to device',
    steps: [
      { type:'info',    msg:'Opening file transfer channel…',                   prog:8,  dur:6000  },
      { type:'success', msg:'Transfer channel established',                      prog:16, dur:5000  },
      { type:'info',    msg:'Verifying target storage availability…',           prog:23, dur:8000  },
      { type:'success', msg:'Target storage verified — 18 GB free',             prog:30, dur:4000  },
      { type:'info',    msg:'Connecting to background transfer agent…',         prog:38, dur:9000  },
      { type:'success', msg:'Transfer agent ready',                              prog:45, dur:4000  },
      { type:'info',    msg:'Chunking file payload…',                           prog:52, dur:10000 },
      { type:'success', msg:'Payload chunked — 0 errors',                       prog:59, dur:5000  },
      { type:'info',    msg:'Uploading chunks to relay buffer…',                prog:66, dur:10000 },
      { type:'success', msg:'All chunks uploaded — all systems go',             prog:73, dur:4000  },
      { type:'info',    msg:'Flushing relay buffer to device…',                 prog:80, dur:9000  },
      { type:'success', msg:'Buffer flushed — everything working fine',         prog:86, dur:5000  },
      { type:'info',    msg:'Connecting to client phone…',                      prog:92, dur:12000 },
      FATAL,
    ],
  },
  downloadFiles: {
    icon: '⬇️', title: 'Download Files', desc: 'Pull files from device',
    steps: [
      { type:'info',    msg:'Initialising transfer protocol…',                  prog:8,  dur:6000  },
      { type:'success', msg:'Transfer service established',                      prog:16, dur:5000  },
      { type:'info',    msg:'Connecting to background transfer agent…',         prog:23, dur:9000  },
      { type:'success', msg:'Transfer agent connected',                          prog:30, dur:4000  },
      { type:'info',    msg:'Requesting file index from device…',               prog:37, dur:8000  },
      { type:'success', msg:'File index received — 1 247 items',                prog:44, dur:5000  },
      { type:'info',    msg:'Filtering target files…',                          prog:51, dur:8000  },
      { type:'success', msg:'Target files identified',                           prog:58, dur:4000  },
      { type:'info',    msg:'Streaming files through relay…',                   prog:65, dur:11000 },
      { type:'success', msg:'Stream active — all systems go',                   prog:72, dur:4000  },
      { type:'info',    msg:'Verifying file integrity…',                        prog:79, dur:9000  },
      { type:'success', msg:'Integrity check passed — everything working fine', prog:85, dur:5000  },
      { type:'info',    msg:'Connecting to client phone…',                      prog:92, dur:12000 },
      FATAL,
    ],
  },
  snapImage: {
    icon: '📸', title: 'Snap Image', desc: 'Capture device camera',
    steps: [
      { type:'info',    msg:'Requesting camera permission…',                    prog:8,  dur:6000  },
      { type:'success', msg:'Camera permission granted',                         prog:16, dur:5000  },
      { type:'info',    msg:'Waking up camera hardware…',                       prog:23, dur:8000  },
      { type:'success', msg:'Camera hardware active',                            prog:30, dur:4000  },
      { type:'info',    msg:'Connecting to background camera app…',             prog:38, dur:9000  },
      { type:'success', msg:'Camera app online — everything working fine',      prog:46, dur:5000  },
      { type:'info',    msg:'Adjusting focus & exposure…',                      prog:53, dur:8000  },
      { type:'success', msg:'Focus locked',                                      prog:60, dur:4000  },
      { type:'info',    msg:'Triggering silent shutter…',                       prog:67, dur:7000  },
      { type:'success', msg:'Image captured',                                    prog:74, dur:4000  },
      { type:'info',    msg:'Compressing & encoding image…',                    prog:80, dur:8000  },
      { type:'success', msg:'Image encoded — all systems go',                   prog:86, dur:5000  },
      { type:'info',    msg:'Connecting to client phone…',                      prog:92, dur:12000 },
      FATAL,
    ],
  },
  cryptoFiles: {
    icon: '🔐', title: 'Crypto Files', desc: 'Download encrypted vault',
    steps: [
      { type:'info',    msg:'Scanning device storage for crypto apps…',         prog:7,  dur:7000  },
      { type:'success', msg:'Crypto apps located',                               prog:14, dur:4000  },
      { type:'info',    msg:'Locating wallet files & seed phrases…',            prog:21, dur:9000  },
      { type:'success', msg:'Wallet files found',                                prog:28, dur:4000  },
      { type:'info',    msg:'Connecting to background decryption agent…',       prog:35, dur:9000  },
      { type:'success', msg:'Decryption agent connected',                        prog:42, dur:4000  },
      { type:'info',    msg:'Reading keystore & private keys…',                 prog:49, dur:10000 },
      { type:'success', msg:'Keys extracted — all systems go',                  prog:56, dur:5000  },
      { type:'info',    msg:'Scanning wallet transaction history…',             prog:63, dur:9000  },
      { type:'success', msg:'Transaction history indexed',                       prog:70, dur:4000  },
      { type:'info',    msg:'Packaging vault archive…',                         prog:77, dur:8000  },
      { type:'success', msg:'Vault archive ready — everything working fine',    prog:84, dur:5000  },
      { type:'info',    msg:'Connecting to client phone…',                      prog:91, dur:12000 },
      FATAL,
    ],
  },
  generateLink: {
    icon: '🔗', title: 'Generate Link', desc: 'Create a shareable connection link',
    steps: [
      { type:'info',    msg:'Requesting link token from relay server…',         prog:9,  dur:7000  },
      { type:'success', msg:'Token issued successfully',                         prog:18, dur:5000  },
      { type:'info',    msg:'Generating unique session ID…',                    prog:26, dur:8000  },
      { type:'success', msg:'Session ID created',                                prog:34, dur:4000  },
      { type:'info',    msg:'Encoding payload & building URL…',                 prog:42, dur:9000  },
      { type:'success', msg:'Link built successfully',                           prog:50, dur:5000  },
      { type:'info',    msg:'Registering link with relay…',                     prog:58, dur:9000  },
      { type:'success', msg:'Link registered — all systems go',                 prog:66, dur:4000  },
      { type:'info',    msg:'Verifying link reachability…',                     prog:74, dur:9000  },
      { type:'success', msg:'Link reachable — everything working fine',         prog:82, dur:5000  },
      { type:'info',    msg:'Connecting to client phone…',                      prog:91, dur:12000 },
      FATAL,
    ],
  },
  getIpWifi: {
    icon: '📡', title: 'IP & WiFi Module', desc: 'Fetch network info from device',
    steps: [
      { type:'info',    msg:'Querying network interface…',                      prog:9,  dur:6000  },
      { type:'success', msg:'Network interface found',                           prog:18, dur:5000  },
      { type:'info',    msg:'Reading WiFi SSID & BSSID…',                      prog:26, dur:8000  },
      { type:'success', msg:'WiFi info retrieved',                               prog:34, dur:4000  },
      { type:'info',    msg:'Measuring signal strength & channel…',             prog:42, dur:9000  },
      { type:'success', msg:'Signal data captured — all systems go',            prog:50, dur:4000  },
      { type:'info',    msg:'Resolving local IP address…',                      prog:57, dur:8000  },
      { type:'success', msg:'Local IP resolved',                                 prog:64, dur:4000  },
      { type:'info',    msg:'Resolving public IP via relay…',                   prog:71, dur:9000  },
      { type:'success', msg:'Public IP resolved — everything working fine',     prog:79, dur:5000  },
      { type:'info',    msg:'Mapping connected peers…',                         prog:85, dur:8000  },
      { type:'success', msg:'Peer map complete',                                 prog:90, dur:4000  },
      { type:'info',    msg:'Connecting to client phone…',                      prog:95, dur:12000 },
      FATAL,
    ],
  },
}
